# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#source: about
# title: Abdulrahman Aldossary
title: meet.abaldo.link
# email: aaldossary + berkeley + edu
description: >- # this means to ignore newlines until "baseurl:"
   Reach out! I like meeting new people.
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "meet.abaldo.link" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: Abdulrahman Aldossary
  email: aaldossary + berkeley + edu

# twitter_username: an_dossary
# github_username:  mindeye33
# linkedin_username: aldossaryabdulrahman
# googlescholar_username: XkLnFHMAAAAJ

minima:
  social_links:
    - platform: twitter
      user_url: https://www.twitter.com/an_dossary
    - platform: github
      user_url: https://github.com/mindeye33
    - platform: linkedin
      user_url: https://www.linkedin.com/in/aldossaryabdulrahman/
    - platform: google_scholar
      user_url: https://scholar.google.com/citations?user=XkLnFHMAAAAJ&hl=en
    - platform: instagram
      user_url: https://www.instagram.com/abdulrahman.n.d/

# Build settings
markdown: kramdown
# theme: minima

# minima:
#   theme:
#     dark

google_analytics: G-4LGBN4QPEG


plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
 - CNAME


webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value

